import os  
import json  
import tempfile  
import re  
import logging  
import uuid  
import base64  
from io import BytesIO  
from pathlib import Path  
from dataclasses import dataclass  
from typing import Optional, List  
from activities_shared.models.custom_activity_request import CustomActivityRequest  
from activities_shared.models.custom_activity_response import CustomActivityResponse, WorkflowResultCode  
from activities_shared.util.base_custom_activity_runner import BaseCustomActivityRunner  
from cars_storage.random_access.rendition import RenditionStorageService  
from cars_storage.execution_journal.data_models import ExecutionLedgersMetadata, LedgerItemsRenditions  
from dataclasses_json import dataclass_json, LetterCase  
from gcs_jsonlogger.ExecutionContextCategory import ExecutionContextCategory  
from cars_storage.random_access.rendition.data_models import PostRenditionParameters  
from gcs_common.exceptions import ContextualException  
from gcs_common.reason_codes import ReasonCode
  
# Try to import PyMuPDF for HTML→PDF conversion  
try:  
    import fitz  # PyMuPDF  
    HTML_TO_PDF_AVAILABLE = True  
except ImportError:  
    HTML_TO_PDF_AVAILABLE = False  
    fitz = None  
    print("Warning: PyMuPDF not available, HTML→PDF conversion will be disabled")
  
# BeautifulSoup is now a required dependency for cleanup  
try:  
    from bs4 import BeautifulSoup  
    BS4_AVAILABLE = True  
except ImportError:  
    BS4_AVAILABLE = False  
    print("Warning: BeautifulSoup4 not available. It's recommended for HTML cleanup.")
  
# Import the image-based PDF processor (Claude Vision approach)  
from pdf_processor import ImageBasedPDFConverter

  
@dataclass_json(letter_case=LetterCase.CAMEL)  
@dataclass  
class RenditionCriteria:  
    rendition_type_code: str  
    rendition_sub_type_code: Optional[str] = None  
    rendition_sub_type_designator_code: Optional[str] = None  
    media_type: Optional[str] = None

  
@dataclass_json(letter_case=LetterCase.CAMEL)  
@dataclass  
class ProcessingConfig:  
    """Configuration for document processing"""  
    image_dpi: int = 450  
    generate_pdf_output: bool = False

  
class HTMLToPDFConverter:  
    """  
    Converts textual HTML to a PDF document using PyMuPDF's Story API.  
    This class is designed to render the structured HTML generated by the AI model.  
    """  
    def __init__(self):  
        self.logger = logging.getLogger(__name__)  
        if not HTML_TO_PDF_AVAILABLE:  
            raise ImportError("PyMuPDF (fitz) is not available. Cannot create HTMLToPDFConverter.")
  
    def convert_html_to_pdf(self, html_path: str) -> bytes:  
        """  
        Converts an HTML file to a PDF using PyMuPDF's rendering engine.
  
        Args:  
            html_path: The file path to the HTML document.
  
        Returns:  
            The generated PDF content as bytes.  
        """  
        try:  
            with open(html_path, 'r', encoding='utf-8') as f:  
                html_content = f.read()
  
            self.logger.info("Converting text-based HTML to PDF using PyMuPDF Story API.")  
            pdf_bytes = self._render_html_with_story(html_content)
  
            if not pdf_bytes:  
                raise Exception("PDF generation with Story API produced no output.")
  
            self.logger.info(f"✓ PDF successfully generated from HTML: {len(pdf_bytes)} bytes")  
            return pdf_bytes
  
        except Exception as e:  
            error_msg = f"Error in HTML-to-PDF conversion: {str(e)}"  
            self.logger.error(error_msg)  
            # As a last resort, create a PDF with the error message  
            return self._create_error_pdf(error_msg)
  
    def _render_html_with_story(self, html_content: str) -> Optional[bytes]:  
        """  
        Renders HTML content to a PDF using the PyMuPDF Story and DocumentWriter API.  
        This method is suitable for structured, text-based HTML.
  
        Args:  
            html_content: The HTML content as a string.
  
        Returns:  
            The generated PDF as bytes, or None on failure.  
        """  
        temp_output_path = f"/tmp/story_output_{uuid.uuid4()}.pdf"  
        try:  
            # The Story API works best with content inside the <body> tag  
            if BS4_AVAILABLE:  
                soup = BeautifulSoup(html_content, 'html.parser')  
                body_content = soup.body.decode_contents() if soup.body else html_content  
            else:  
                body_content = html_content
  
            story = fitz.Story(html=body_content)  
            writer = fitz.DocumentWriter(temp_output_path)
              
            # Use a standard page size like 'letter'  
            page_rect = fitz.paper_rect("letter")  
            more = 1  
            while more:  
                device = writer.begin_page(page_rect)  
                more, _ = story.place(page_rect)  
                story.draw(device)  
                writer.end_page()
  
            writer.close()
  
            with open(temp_output_path, 'rb') as f:  
                pdf_bytes = f.read()
  
            self.logger.info(f"PyMuPDF Story API generated a PDF of {len(pdf_bytes)} bytes.")  
            return pdf_bytes
  
        except Exception as e:  
            self.logger.error(f"PyMuPDF Story API failed: {e}")  
            return None  
        finally:  
            if os.path.exists(temp_output_path):  
                os.remove(temp_output_path)
  
    def _create_error_pdf(self, error_message: str) -> bytes:  
        """  
        Creates a simple PDF document containing an error message.  
        This is a fallback for when the primary conversion fails.
  
        Args:  
            error_message: The error message to include in the PDF.
          
        Returns:  
            A PDF file as bytes.  
        """  
        try:  
            doc = fitz.open()  
            page = doc.new_page()  
            rect = page.rect + (50, 50, -50, -50)  
            page.insert_textbox(rect, f"PDF Generation Failed:\n\n{error_message}", fontsize=12, fontname="helv")  
            pdf_bytes = doc.tobytes()  
            doc.close()  
            return pdf_bytes  
        except Exception as e:  
            # If even this fails, we cannot proceed.  
            raise Exception(f"All PDF creation methods failed. Final error: {e}")
  
# ... (The rest of main.py remains the same, as the CustomActivityRunner logic is sound)  
# This includes CustomActivityRunner and all its methods.  
# The refactored HTMLToPDFConverter will now be correctly used by _convert_html_to_pdf method.  
# For brevity, the unchanged part of main.py is omitted here, but should be included in the final file.  
# The original file content for CustomActivityRunner and its helper methods is correct.  
class CustomActivityRunner(BaseCustomActivityRunner):
                  
    def run(self, activity_request: CustomActivityRequest) -> CustomActivityResponse:                  
        """                  
        Document processing workflow:                  
        1. pdf_processor.py → PDF→HTML using Claude Vision API          
        2. HTMLToPDFConverter → HTML→PDF using PyMuPDF Story API          
        """                  
        self._logger.info("=" * 80)          
        self._logger.info(f"Starting IMAGE-BASED document processing workflow (Claude Vision - Enhanced)")          
        self._logger.info(f"Activity Execution GUID: {activity_request.activity_execution_guid}")          
        self._logger.info(f"Workflow Execution ID: {activity_request.workflow_execution_id}")
                  
        if activity_request.inputs:          
            inputs_info = f"Type: {type(activity_request.inputs)}"          
            if isinstance(activity_request.inputs, dict):          
                inputs_info += f", Keys: {list(activity_request.inputs.keys())}"          
            self._logger.info(f"Input data present: {inputs_info}")          
        else:          
            self._logger.warn("⚠️  No inputs provided to activity")
                  
        self._logger.info("=" * 80)
                          
        temp_files_to_cleanup = []
                          
        try:                  
            config = self._parse_processing_config(activity_request)                  
            self._logger.info(f"Processing configuration: DPI={config.image_dpi}, "                  
                            f"generate_pdf={config.generate_pdf_output}")
                              
            workflow_execution_id: int = activity_request.workflow_execution_id                  
            storage_service = RenditionStorageService(cars_http_client=self._cars_http_client)
                  
            # STEP 0: Get Input PDF      
            input_rend, input_meta, pdf_data = self._get_input_pdf(                  
                activity_request, workflow_execution_id, storage_service                  
            )
                              
            temp_pdf_path = f"/tmp/{input_meta.file_name}"                  
            with open(temp_pdf_path, 'wb') as f:                  
                f.write(pdf_data)                  
            temp_files_to_cleanup.append(temp_pdf_path)                  
            self._logger.info(f"Saved PDF to: {temp_pdf_path}")
                  
            # STEP 1: PDF → HTML (Claude Vision)      
            html_bytes, html_file_path, conversion_stats = self._convert_pdf_to_html_image_based(                  
                temp_pdf_path, config, temp_files_to_cleanup                  
            )
                  
            # STEP 2: Post HTML Rendition      
            self._logger.info("STEP 2: Posting HTML rendition...")          
            html_guid = self._post_html_rendition(                  
                storage_service, input_rend, input_meta,                   
                html_bytes, html_file_path                  
            )
                  
            # STEP 3: HTML → PDF (Image Extraction)      
            pdf_guid = None                  
            if config.generate_pdf_output:                  
                self._logger.info("STEP 3: Converting HTML→PDF using PyMuPDF Story API...")
                          
                if not HTML_TO_PDF_AVAILABLE:          
                    raise ContextualException(          
                        "PDF generation requested but PyMuPDF not available",          
                        reason_code=ReasonCode.GCS_WORKFLOW_INTERNAL_ERROR,          
                        reason_text="PyMuPDF should be available from requirements.txt"          
                    )
                          
                pdf_guid = self._convert_html_to_pdf(                  
                    html_file_path, storage_service, input_rend, input_meta,                   
                    html_guid, temp_files_to_cleanup                  
                )
                          
                if not pdf_guid:          
                    raise ContextualException(          
                        "PDF generation failed",          
                        reason_code=ReasonCode.GCS_WORKFLOW_INTERNAL_ERROR,          
                        reason_text="HTML→PDF conversion did not produce output"          
                    )          
            else:          
                self._logger.info("STEP 3: Skipping HTML→PDF conversion (disabled in config)")
                  
            # STEP 4: Cleanup      
            self._logger.info("STEP 4: Cleaning up temporary files...")          
            self._cleanup_temp_files(temp_files_to_cleanup)
                              
            return self._create_success_response(                  
                html_guid, pdf_guid, conversion_stats, config                  
            )
                              
        except Exception as e:                  
            self._logger.error(f"Integrated workflow failed: {str(e)}")                  
            self._cleanup_temp_files(temp_files_to_cleanup)
                              
            raise ContextualException(                  
                f"Document processing workflow failed: {str(e)}",                  
                reason_code=ReasonCode.GCS_WORKFLOW_INTERNAL_ERROR,                  
                reason_text=str(e)                  
            )
                  
    def _parse_processing_config(self, activity_request: CustomActivityRequest) -> ProcessingConfig:                  
        attrs = activity_request.execution_attributes or {}
                          
        return ProcessingConfig(          
            image_dpi=int(attrs.get('imageDpi', 450)),  
            generate_pdf_output=attrs.get('generatePdfOutput', False)    
        )
              
    def _get_input_pdf(self, activity_request, workflow_execution_id, storage_service):                  
        self._logger.info(f"Received execution attributes: {activity_request.execution_attributes}")          
        self._logger.info(f"Received inputs: {activity_request.inputs}")
                  
        input_rendition_guid = None          
        if activity_request.inputs and 'acquiredObject' in activity_request.inputs:          
            acquired_object = activity_request.inputs['acquiredObject']          
            input_rendition_guid = acquired_object.get('renditionGuid')          
            self._logger.info(f"✓ Found rendition GUID in inputs: {input_rendition_guid}")
          
        if not input_rendition_guid:          
            self._logger.info("No rendition in inputs, checking execution ledger...")          
            execution_ledgers_metadata: ExecutionLedgersMetadata = self.get_execution_ledger(workflow_execution_id)
                      
            if (execution_ledgers_metadata and           
                execution_ledgers_metadata.ledger_items and           
                execution_ledgers_metadata.ledger_items.renditions):
                          
                input_rendition_criteria: RenditionCriteria = RenditionCriteria(          
                    rendition_type_code='SOURCE',          
                    rendition_sub_type_code='PDF',          
                    media_type='application/pdf'          
                )
          
                input_renditions = self.get_renditions_from_execution_ledger(          
                    execution_ledgers_metadata,          
                    input_rendition_criteria          
                )
                          
                if not input_renditions:          
                    general_criteria = RenditionCriteria(rendition_type_code='SOURCE')          
                    input_renditions = self.get_renditions_from_execution_ledger(          
                        execution_ledgers_metadata,          
                        general_criteria          
                    )
                          
                if input_renditions:          
                    input_rendition_guid = input_renditions[0].rendition_guid          
                    self._logger.info(f"✓ Found rendition GUID in ledger: {input_rendition_guid}")
          
        if not input_rendition_guid:          
            raise ContextualException(          
                "No input rendition found in inputs or execution ledger",          
                reason_code=ReasonCode.GCS_WORKFLOW_INTERNAL_ERROR,          
                reason_text="No PDF input rendition available for processing"          
            )
          
        input_meta = storage_service.get_rendition_by_guid(input_rendition_guid)          
        self._logger.info(f"Retrieved rendition: {input_meta.file_name}")
          
        pdf_data = storage_service.get_rendition_data(input_rendition_guid)          
        self._logger.info(f"Downloaded PDF data: {len(pdf_data)} bytes")
                  
        class InputRendition:          
            def __init__(self, guid):          
                self.rendition_guid = guid
                  
        input_rend = InputRendition(input_rendition_guid)
                          
        return input_rend, input_meta, pdf_data
                  
    def _convert_pdf_to_html_image_based(self, temp_pdf_path, config, temp_files_to_cleanup):                  
        self._logger.info("Using ENHANCED image-based converter (pdf_processor.py with Claude Vision)...")
                          
        converter = ImageBasedPDFConverter()
                          
        result = converter.convert_pdf_to_html(                  
            pdf_path=temp_pdf_path,                  
            output_file=f"/tmp/image_based_{uuid.uuid4()}.html",                  
            start_page=0,          
            end_page=None,                  
            dpi=config.image_dpi  
        )
                          
        if not result.get("success"):                  
            raise ContextualException(                  
                "Image-based HTML conversion failed",                  
                reason_code=ReasonCode.GCS_WORKFLOW_INTERNAL_ERROR,                  
                reason_text=f"Error: {result.get('error', 'Unknown')}"                  
            )
                          
        html_file_path = result.get("output_file")                  
        temp_files_to_cleanup.append(html_file_path)
                          
        with open(html_file_path, 'rb') as f:                  
            html_bytes = f.read()
                          
        stats = {                  
            "method": "image-based-enhanced-v2",                  
            "pages_processed": result.get("total_pages", 0),                  
            "successful_pages": result.get("successful_pages", 0),                  
            "failed_pages": result.get("failed_pages", 0)                  
        }
                          
        self._logger.info(f"Enhanced image-based conversion complete: {len(html_bytes)} bytes")
                          
        return html_bytes, html_file_path, stats
                  
    def _create_output_rendition(self, combined_html: str, input_rendition,           
                                input_meta, output_crit: RenditionCriteria,           
                                storage: RenditionStorageService) -> str:          
        out_guid = str(uuid.uuid4())          
        base = os.path.splitext(input_meta.file_name)[0]          
        out_name = f"{base}.html"
                  
        post = PostRenditionParameters(          
            derived_from_rendition_guid=input_rendition.rendition_guid,          
            file_name=out_name,          
            rendition_guid=out_guid,          
            rendition_type_code=output_crit.rendition_type_code,          
            rendition_sub_type_code=output_crit.rendition_sub_type_code,          
            rendition_sub_type_designator_code=output_crit.rendition_sub_type_designator_code,          
            media_type="text/html",          
            resource_group_id=input_meta.resource_group_id,          
            revision_guid=input_meta.revision_guid,          
        )
                  
        storage.post_rendition(post, combined_html.encode("utf-8"))          
        self._logger.info(f"✓ Created output rendition: {out_guid}")          
        return out_guid
              
    def _post_html_rendition(self, storage_service, input_rend, input_meta,                   
                            html_bytes, html_file_path):                  
        output_crit = RenditionCriteria(          
            rendition_type_code="SOURCE",          
            rendition_sub_type_code="CONVERTED",          
            rendition_sub_type_designator_code=None,          
            media_type="text/html"          
        )
                  
        html_content = html_bytes.decode('utf-8') if isinstance(html_bytes, bytes) else html_bytes
                  
        html_guid = self._create_output_rendition(          
            html_content, input_rend, input_meta, output_crit, storage_service          
        )
                          
        return html_guid
                  
    def _convert_html_to_pdf(self, html_file_path, storage_service, input_rend, input_meta,                   
                            html_guid, temp_files_to_cleanup):                  
        """Convert textual HTML to PDF using the corrected converter."""
                          
        try:                  
            converter = HTMLToPDFConverter()          
            pdf_bytes = converter.convert_html_to_pdf(html_file_path)
                              
            self._logger.info(f"Generated PDF: {len(pdf_bytes)} bytes")
                      
            pdf_guid = str(uuid.uuid4())          
            base = os.path.splitext(input_meta.file_name)[0]          
            pdf_name = f"{base}_converted.pdf"
                              
            pdf_post_params = PostRenditionParameters(                  
                derived_from_rendition_guid=html_guid,          
                file_name=pdf_name,          
                rendition_guid=pdf_guid,          
                rendition_type_code="SOURCE",                  
                rendition_sub_type_code="CONVERTED",                  
                rendition_sub_type_designator_code=None,                  
                media_type="application/pdf",                  
                resource_group_id=input_meta.resource_group_id,                  
                revision_guid=input_meta.revision_guid,          
            )
                              
            storage_service.post_rendition(pdf_post_params, pdf_bytes)          
            self._logger.info(f"✓ PDF rendition created: {pdf_guid}")
                              
            return pdf_guid
                              
        except Exception as e:                  
            self._logger.error(f"HTML→PDF conversion failed: {e}")          
            raise ContextualException(          
                f"HTML→PDF conversion failed: {str(e)}",          
                reason_code=ReasonCode.GCS_WORKFLOW_INTERNAL_ERROR,          
                reason_text=str(e)          
            )
                  
    def _cleanup_temp_files(self, temp_files_to_cleanup):                  
        for temp_file in temp_files_to_cleanup:                  
            if os.path.exists(temp_file):                  
                try:                  
                    os.remove(temp_file)                  
                    self._logger.info(f"Cleaned up: {temp_file}")                  
                except Exception as e:                  
                    self._logger.warn(f"Failed to cleanup {temp_file}: {e}")
                  
    def _create_success_response(self, html_guid, pdf_guid, conversion_stats, config):                  
        output_attrs = {                  
            "htmlRendition": {                  
                "renditionGuid": html_guid,                  
                "conversionMethod": "image-based-enhanced-v2 (Claude Vision with refined prompt)",                  
                "pagesProcessed": conversion_stats.get("pages_processed", 0),          
                "successfulPages": conversion_stats.get("successful_pages", 0),          
                "failedPages": conversion_stats.get("failed_pages", 0)          
            },                  
            "processingConfig": {                  
                "imageDpi": config.image_dpi,          
                "generatePdfOutput": config.generate_pdf_output,            
                "htmlToPdfAvailable": HTML_TO_PDF_AVAILABLE,        
                "htmlToPdfMethod": "PyMuPDF Story API from textual HTML",    
                "enhancements": "Refined AI prompt, robust HTML cleanup, corrected PDF rendering logic"  
            }                  
        }
                          
        if pdf_guid:                  
            output_attrs["pdfRendition"] = {                  
                "renditionGuid": pdf_guid,                  
                "derivedFrom": html_guid,          
                "status": "success"          
            }            
        elif config.generate_pdf_output:          
            output_attrs["pdfRendition"] = {            
                "status": "failed",            
                "reason": "PDF generation was requested but failed"            
            }
                          
        return CustomActivityResponse(                  
            result_code=WorkflowResultCode.SUCCEEDED,                  
            output_attributes=output_attrs                  
        )
                  
    def get_execution_ledger(self, workflow_execution_id: int) -> ExecutionLedgersMetadata:                  
        url = f"{os.getenv('EXECUTION_JOURNAL_BASE_URL')}/v1/execution-ledgers/{workflow_execution_id}"                  
        response: dict = self._cars_http_client.get(                  
            url=url,                  
            params={},                  
            execution_context_category=ExecutionContextCategory.OPTIONAL_BASE_ONLY,                  
            headers={'Content-Type': 'application/json'}                  
        )                  
        return ExecutionLedgersMetadata.from_dict(response)
                  
    @staticmethod                  
    def get_renditions_from_execution_ledger(                  
        ledger_metadata: ExecutionLedgersMetadata,                  
        rendition_criteria: RenditionCriteria                  
    ) -> List[LedgerItemsRenditions]:                  
        if not ledger_metadata or not ledger_metadata.ledger_items or not ledger_metadata.ledger_items.renditions:  
            return []
                          
        return [                  
            item for item in ledger_metadata.ledger_items.renditions                  
            if CustomActivityRunner.is_rendition_match(item, rendition_criteria)                  
        ]
                  
    @staticmethod                  
    def is_rendition_match(                  
        ledger_rendition: LedgerItemsRenditions,                  
        rendition_criteria: RenditionCriteria                  
    ) -> bool:                  
        if not ledger_rendition:                  
            return False
                              
        return (                  
            ledger_rendition.rendition_type_code == rendition_criteria.rendition_type_code and                  
            (rendition_criteria.rendition_sub_type_code is None or                  
             ledger_rendition.rendition_sub_type_code == rendition_criteria.rendition_sub_type_code)                  
        )  